image: golang:1.17

variables:
  OUTPUT_FILE: baal

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH
    - if: $CI_COMMIT_TAG

stages:
  - test

Unit:
  stage: test
  rules:
    - if: $CI_COMMIT_BRANCH || $CI_COMMIT_TAG
  script:
    - make test

Race:
  stage: test
  rules:
    - if: $CI_COMMIT_BRANCH || $CI_COMMIT_TAG
  script:
    - make race

Coverage:
  stage: test
  rules:
    - if: $CI_COMMIT_BRANCH || $CI_COMMIT_TAG
  script:
    - make coverage

Cover:
  stage: test
  script:
    - make coverhtml
  rules:
    - if: $CI_COMMIT_BRANCH || $CI_COMMIT_TAG
