version: "3.9"

services:
  mysql:
    image: mysql:5.7
    container_name: baal-mysql
    platform: linux/x86_64
    ports:
      - 3306:3306
    networks:
      - baal-net
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_USER: baal
      MYSQL_DATABASE: baal
      MYSQL_PASSWORD: ${BAAL_MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${BAAL_MYSQL_ROOT_PASSWORD}
      TZ: Asia/Taipei
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "--user=baal",
          "--password=${BAAL_MYSQL_PASSWORD}"
        ]
      interval: 60s
      timeout: 30s
      start_period: 30s
      retries: 3
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: baal-phpmyadmin
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - 8001:80
    networks:
      - baal-net
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_ARBITRARY: 1
      TZ: Asia/Taipei
  migrate:
    build:
      context: .
    container_name: baal-migrate
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - baal-net
    environment:
      TZ: Asia/Taipei
    volumes:
      - ./.env:/.env
      - ./config.yml:/config.yml
    command: [ "migrate", "up" ]
  backend:
    build:
      context: .
    container_name: baal-backend
    restart: on-failure
    depends_on:
      mysql:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully
    ports:
      - 7001:7001
    networks:
      - baal-net
    environment:
      TZ: Asia/Taipei
      PORT: 7001
    volumes:
      - ./.env:/.env
      - ./config.yml:/config.yml
    command: [ "server" ]
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:7001/health" ]
      interval: 10s
      timeout: 10s
      start_period: 10s
      retries: 3
networks:
  baal-net:
    driver: bridge
    name: baal-net
