// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	model "baal/model"

	mock "github.com/stretchr/testify/mock"
)

// UserFace is an autogenerated mock type for the UserFace type
type UserFace struct {
	mock.Mock
}

// GetByQuery provides a mock function with given fields: m
func (_m *UserFace) GetByQuery(m *model.UserSchema) error {
	ret := _m.Called(m)

	var r0 error
	if rf, ok := ret.Get(0).(func(*model.UserSchema) error); ok {
		r0 = rf(m)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
