// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	model "baal/model"

	mock "github.com/stretchr/testify/mock"
)

// UserFace is an autogenerated mock type for the UserFace type
type UserFace struct {
	mock.Mock
}

// GetByQuery provides a mock function with given fields: m
func (_m *UserFace) GetByQuery(m *model.UserSchema) (*model.UserSchema, error) {
	ret := _m.Called(m)

	var r0 *model.UserSchema
	if rf, ok := ret.Get(0).(func(*model.UserSchema) *model.UserSchema); ok {
		r0 = rf(m)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.UserSchema)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*model.UserSchema) error); ok {
		r1 = rf(m)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
